#pragma once

#define PROD_PUMP GPIO_NUM_23
#define REFLUX_PUMP GPIO_NUM_22
#define PROD_FLOW GPIO_NUM_34
#define REFLUX_FLOW GPIO_NUM_35
#define ONEWIRE_BUS GPIO_NUM_15
#define LCD_SCL GPIO_NUM_18
#define LCD_SDA GPIO_NUM_19
#define FAN_SWITCH GPIO_NUM_21
#define INPUT_UP GPIO_NUM_25
#define INPUT_DOWN GPIO_NUM_26
#define INPUT_LEFT GPIO_NUM_27
#define INPUT_MID GPIO_NUM_14
#define ELEMENT_1 GPIO_NUM_13
#define ELEMENT_2 GPIO_NUM_10